### ISSUE TITLE
Crash on mouseover - RaiderIO.GetProfile table structure change

### ISSUE THREAD

**Issue by AySz88** [NinerBull/tRP3_RDotIO#1]
When a tooltip tries to render with a character that has raid data, this crash happens:
```
tRP3_RDotIO/tRP3_RDotIO.lua:294: attempt to index field 'dungeon' (a nil value)
[string "@tRP3_RDotIO/tRP3_RDotIO.lua"]:294: in function <tRP3_RDotIO/tRP3_RDotIO.lua:73>
...
```
It appears that the table returned from RaiderIO.GetProfile has changed to remove "dungeon", i.e:

`thisPlayerTables['raidProfile']["sortedProgress"][z]["progress"]["raid"]["dungeon"]["shortName"]`

should now be:

`thisPlayerTables['raidProfile']["sortedProgress"][z]["progress"]["raid"]["shortName"]`

It looks like this only affects two places, [tRP3_RDotIO/tRP3_RDotIO.lua:294](https://github.com/NinerBull/tRP3_RDotIO/blob/99ecae4d0af4e5e04f718ada50fc38d0d98b7c5d/tRP3_RDotIO/tRP3_RDotIO.lua#L294) and [tRP3_RDotIO/tRP3_RDotIO.lua:304](https://github.com/NinerBull/tRP3_RDotIO/blob/99ecae4d0af4e5e04f718ada50fc38d0d98b7c5d/tRP3_RDotIO/tRP3_RDotIO.lua#LL304C11-L304C12).

**Comment by NinerBull** [comment]
Fixed in commit #b8974a3, thank you!
