### ISSUE TITLE
extremely inconsistent loading

### ISSUE THREAD

**Issue by DarkLCF** [NinerBull/tRP3_RDotIO#2]
When mousing over my own unitframe the tooltip doesn't load anything raider.io related at all, even without other addons. Sometimes it will load it after moving it to a different spot or if i target myself and mouseover the targer frame etc. Sometimes when i previously mouseovered myself and it didn't load anything, and i immediately mouseover another player i will see my own scores on the tooltip of that player instead of his.

same goes for almost all unitframes actually not just my own (target, party etc), and even just mousing over other players in the wold it's pretty inconsistent

**Comment by NinerBull** [comment]
I just released version v1.5.0 that should hopefully fix this. 
Thank you for reporting!
